#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t rr"

$L "                                                                               
$L "          ####  #    # ##### #    #  ####  #####  # ###### ####  #####  #    # 
$L "         #      ##  ## #   # ##  ## #    # #    # # #      #   # #   #  ##  ## 
$L "          ####  # ## # #   # # ## # #    # ###### # #####  ##### #   #  # ## # 
$L "              # #    # #   # #    # #    # #    # # #      #   # #   #  #    # 
$L "              # #    # #   # #    # #    # #    # # #      #   # #   #  #    # 
$L "          ####  #    # ##### #    # ###### #####  # ###### #   # #####  #    # 
 

$L "Welcome to Android `getprop ro.build.version.release` / SmombieRom-`getprop ro.rr.version`";
